### ISSUE TITLE
Some Excel files are not accepted

### ISSUE THREAD

**Issue by hdurand** [okfn/goodtables#56]
If I run [spd-admin](https://github.com/okfn/spd-admin) on a `sources.csv` with Excel files, goodtables raises exceptions for some of them.

Examples:

With this file:
https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/85779/AnnexDGPCTransactionsdataSeptember2011.xlsx

Goodtables raises:
```
  File "goodtables/pipeline/pipeline.py", line 122, in __init__
    raise exceptions.PipelineBuildError(e.msg)
goodtables.exceptions.PipelineBuildError: The data source appears to be an HTML document.
```

With this file:
https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/5731/1878709.xls

Goodtables raises:
```
  File "goodtables/datatable/datatable.py", line 195, in get_headers
    for index, line in enumerate(reader):
_csv.Error: line contains NULL byte
```

**Comment by pwalsh** [comment]
@hdurand that makes sense because spd-admin is a high-level wrapper around a Good Tables `pipeline.Batch` class, providing the extra run/results logic, but it does not expose the full Good Tables API via the spd-admin `run` command.

What that means is:

* Good Tables supports XLS if you explicitly pass a `format='xls'` ([ref](https://github.com/okfn/goodtables/blob/master/goodtables/pipeline/pipeline.py#L59))
* SPD-Admin only supports CSV (there is no API to say, for this particular file, instantiate the Good Tables pipeline with `format='xls'`). 

To support this, you'd have to pass in a `format` argument to the pipeline constructor for each file in your `sources.csv`.

* Here are the default args for a pipeline (for all files in a batch): https://github.com/okfn/spd-admin/blob/master/spd_admin/main.py#L39
* Here the batch is instantiated: https://github.com/okfn/spd-admin/blob/master/spd_admin/main.py#L60
* Here a pipeline is constructed for each file in `sources.csv`: https://github.com/okfn/goodtables/blob/master/goodtables/pipeline/batch.py#L125
* So you'd have to have [this class](https://github.com/okfn/goodtables/blob/master/goodtables/pipeline/batch.py#L104) changed to accept `data['format']` or whatever from the sources.csv, thereby setting format for each file

**Comment by tryggvib** [comment]
@rgrp Do you reckon we should fix this?

**Comment by pwalsh** [comment]
Closing this, as it is not a good tables issue. I opened a placeholder on spd-admin: https://github.com/okfn/spd-admin/issues/3
